config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'

  resources :questions do
    resources :answers, shallow: true, only: %i[create update destroy]
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :author, class_name: 'User'

  validates :body, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :answers, dependent: :destroy

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, foreign_key: :author_id, dependent: :destroy
  has_many :answers, foreign_key: :author_id, dependent: :destroy
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer, only: %i[update destroy]

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params)
    @answer.author = current_user
    @answer.save
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    if @answer.author == current_user
      @answer.destroy
      redirect_to question_path(@answer.question)
    else
      redirect_to question_path(@answer.question), notice: 'Only authored answers allowed for deletion'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_question, only: %i[show edit update destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if @question.save
      redirect_to question_path(@question), notice: 'Your question successfully created'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    if @question.author == current_user
      @question.destroy
      redirect_to questions_path
    else
      redirect_to questions_path, notice: 'Only authored questions allowed for deletion'
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def user_is_an_author?(user)
    user == current_user
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/answers/_answer.html.slim
tr id= answer.id
  td= answer.body
  - if user_signed_in? && user_is_an_author?(answer.author)

    td= form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
      = f.label :body, 'Your answer'
      = f.text_area :body
      = f.submit 'save'

    td= link_to 'edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

    td= link_to 'delete',
          answer_path(answer),
          method: :delete,
          data: { confirm: 'confirm', name: answer.body }

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>')

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>')
  $('.new-answer #answer_body').val('')
<% end %>

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>')

<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render @question.answers %>')
<% end %>

app/views/layouts/application.html.slim
doctype 5
html
  head
    title = 'Qna'
    = csrf_meta_tag
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    p= notice
    p= alert
    = render 'shared/nav'
    = yield

app/views/questions/_form.html.slim
= form_with model: @question, local: true do |f|
  = render 'shared/errors', resource: @question
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.submit 'Ask'

app/views/questions/_question.html.slim
tr id = question.id
  td= question.title
  td= question.body

  td= link_to 'show', question_path(question)
  - if user_signed_in? && user_is_an_author?(question.author)

    td= form_with model: question, local: false, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
      = f.label :title, 'Your title'
      = f.text_field :title
      = f.label :body, 'Your question'
      = f.text_area :body
      = f.submit 'save'

    td= link_to 'edit', '#', class: 'edit-question-link', data: { question_id: question.id }

    td= link_to 'delete',
              question_path(question),
              method: :delete,
              data: { confirm: 'confirm', name: question.body }

app/views/questions/edit.html.slim
h1= 'Edit question'
= render 'form'

app/views/questions/index.html.slim
.question-errors

.questions
  table
    thead
      tr
        th 'Title'
        th 'Body'
    tbody
      = render @questions

p= @questions.count
p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
h1= 'New question'
= render 'form'

app/views/questions/show.html.slim
h1= @question.title
p= @question.body

h1= 'Answer to question'

.answer-errors

- if user_signed_in?
  = form_with model: [@question, @answer ], local: false, class: 'new-answer' do |f|
    = f.label :body
    = f.text_area :body
    = f.submit 'Answer'

.answers
  table
    thead
      tr
        th 'Body'
        th 'Delete'
    tbody
      = render @question.answers

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>')

<% if !@question.errors.present? %>
  $('.questions').html('<%= j render @question %>')
<% end %>

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_nav.html.slim
nav.navbar-light.bg-light
  - if user_signed_in?
    li = link_to 'log out', destroy_user_session_path, method: :delete
  - else
    li = link_to 'log in', new_user_session_path
    li = link_to 'sign up', new_user_registration_path